name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Enable pnpm
        run: corepack enable

      - name: Install dependencies
        run: pnpm install

      - name: Lint & fix
        run: pnpm eslint . --fix

      - name: Prettier check
        run: pnpm prettier --check .

      - name: Run tests
        run: pnpm test

      - name: Build
        run: pnpm build
