name: CI with pnpm

on:
  # Ajuste quais eventos vão disparar o workflow
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-lint-test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [18]

    steps:
      # Faz checkout do seu código
      - uses: actions/checkout@v4

      # Instala Node.js na versão escolhida
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      # Instala o pnpm globalmente
      - name: Install pnpm
        run: npm install -g pnpm@9.15.5

      # Verifica versão do pnpm
      - name: Check pnpm version
        run: pnpm --version

      # Instala dependências do seu projeto
      - name: Install dependencies
        run: pnpm install

      # Exemplo de lint
      - name: Lint
        run: pnpm run lint

      # Exemplo de testes
      - name: Run tests
        run: pnpm test

      # Exemplo de build
      - name: Build
        run: pnpm build
